package kolomyichuk.runly.ui.theme

import androidx.compose.ui.graphics.Color

//Light

val primaryLight = Color(0xFF006E1F)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF3ADC55)
val onPrimaryContainerLight = Color(0xFF005C18)
val secondaryLight = Color(0xFF236C2B)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFA5F2A1)
val onSecondaryContainerLight = Color(0xFF28702F)
val tertiaryLight = Color(0xFF00677E)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF00D1FD)
val onTertiaryContainerLight = Color(0xFF005669)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF3FCEC)
val onBackgroundLight = Color(0xFF151E14)
val surfaceLight = Color(0xFFF3FCEC)
val onSurfaceLight = Color(0xFF151E14)
val surfaceVariantLight = Color(0xFFD7E7D1)
val onSurfaceVariantLight = Color(0xFF3D4A3A)
val outlineLight = Color(0xFF6D7B69)
val outlineVariantLight = Color(0xFFBBCBB6)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2A3328)
val inverseOnSurfaceLight = Color(0xFFEAF4E4)
val inversePrimaryLight = Color(0xFF43E35B)
val surfaceDimLight = Color(0xFFD3DDCE)
val surfaceBrightLight = Color(0xFFF3FCEC)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEDF7E7)
val surfaceContainerLight = Color(0xFFE7F1E1)
val surfaceContainerHighLight = Color(0xFFE1EBDC)
val surfaceContainerHighestLight = Color(0xFFDCE5D6)


//Dark

val primaryDark = Color(0xFF5DF96E)
val onPrimaryDark = Color(0xFF00390C)
val primaryContainerDark = Color(0xFF3ADC55)
val onPrimaryContainerDark = Color(0xFF005C18)
val secondaryDark = Color(0xFF8DD88A)
val onSecondaryDark = Color(0xFF00390C)
val secondaryContainerDark = Color(0xFF035517)
val onSecondaryContainerDark = Color(0xFF7FCA7D)
val tertiaryDark = Color(0xFFA1E6FF)
val onTertiaryDark = Color(0xFF003543)
val tertiaryContainerDark = Color(0xFF00D1FD)
val onTertiaryContainerDark = Color(0xFF005669)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0D150C)
val onBackgroundDark = Color(0xFFDCE5D6)
val surfaceDark = Color(0xFF0D150C)
val onSurfaceDark = Color(0xFFDCE5D6)
val surfaceVariantDark = Color(0xFF3D4A3A)
val onSurfaceVariantDark = Color(0xFFBBCBB6)
val outlineDark = Color(0xFF869582)
val outlineVariantDark = Color(0xFF3D4A3A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDCE5D6)
val inverseOnSurfaceDark = Color(0xFF2A3328)
val inversePrimaryDark = Color(0xFF006E1F)
val surfaceDimDark = Color(0xFF0D150C)
val surfaceBrightDark = Color(0xFF333C31)
val surfaceContainerLowestDark = Color(0xFF081008)
val surfaceContainerLowDark = Color(0xFF151E14)
val surfaceContainerDark = Color(0xFF192218)
val surfaceContainerHighDark = Color(0xFF242C22)
val surfaceContainerHighestDark = Color(0xFF2E372D)


