package kolomyichuk.runly.ui.theme

import androidx.compose.ui.graphics.Color

//Light

val primaryLight = Color(color = 0xFF006E1F)
val onPrimaryLight = Color(color = 0xFFFFFFFF)
val primaryContainerLight = Color(color = 0xFF3ADC55)
val onPrimaryContainerLight = Color(color = 0xFF005C18)
val secondaryLight = Color(color = 0xFF236C2B)
val onSecondaryLight = Color(color = 0xFFFFFFFF)
val secondaryContainerLight = Color(color = 0xFFA5F2A1)
val onSecondaryContainerLight = Color(color = 0xFF28702F)
val tertiaryLight = Color(color = 0xFF00677E)
val onTertiaryLight = Color(color = 0xFFFFFFFF)
val tertiaryContainerLight = Color(color = 0xFF00D1FD)
val onTertiaryContainerLight = Color(color = 0xFF005669)
val errorLight = Color(color = 0xFFBA1A1A)
val onErrorLight = Color(color = 0xFFFFFFFF)
val errorContainerLight = Color(color = 0xFFFFDAD6)
val onErrorContainerLight = Color(color = 0xFF93000A)
val backgroundLight = Color(color = 0xFFF3FCEC)
val onBackgroundLight = Color(color = 0xFF151E14)
val surfaceLight = Color(color = 0xFFF3FCEC)
val onSurfaceLight = Color(color = 0xFF151E14)
val surfaceVariantLight = Color(color = 0xFFD7E7D1)
val onSurfaceVariantLight = Color(color = 0xFF3D4A3A)
val outlineLight = Color(color = 0xFF6D7B69)
val outlineVariantLight = Color(color = 0xFFBBCBB6)
val scrimLight = Color(color = 0xFF000000)
val inverseSurfaceLight = Color(color = 0xFF2A3328)
val inverseOnSurfaceLight = Color(color = 0xFFEAF4E4)
val inversePrimaryLight = Color(color = 0xFF43E35B)
val surfaceDimLight = Color(color = 0xFFD3DDCE)
val surfaceBrightLight = Color(color = 0xFFF3FCEC)
val surfaceContainerLowestLight = Color(color = 0xFFFFFFFF)
val surfaceContainerLowLight = Color(color = 0xFFEDF7E7)
val surfaceContainerLight = Color(color = 0xFFE7F1E1)
val surfaceContainerHighLight = Color(color = 0xFFE1EBDC)
val surfaceContainerHighestLight = Color(color = 0xFFDCE5D6)


//Dark

val primaryDark = Color(color = 0xFF5DF96E)
val onPrimaryDark = Color(color = 0xFF00390C)
val primaryContainerDark = Color(color = 0xFF3ADC55)
val onPrimaryContainerDark = Color(color = 0xFF005C18)
val secondaryDark = Color(color = 0xFF8DD88A)
val onSecondaryDark = Color(color = 0xFF00390C)
val secondaryContainerDark = Color(color = 0xFF035517)
val onSecondaryContainerDark = Color(color = 0xFF7FCA7D)
val tertiaryDark = Color(color = 0xFFA1E6FF)
val onTertiaryDark = Color(color = 0xFF003543)
val tertiaryContainerDark = Color(color = 0xFF00D1FD)
val onTertiaryContainerDark = Color(color = 0xFF005669)
val errorDark = Color(color = 0xFFFFB4AB)
val onErrorDark = Color(color = 0xFF690005)
val errorContainerDark = Color(color = 0xFF93000A)
val onErrorContainerDark = Color(color = 0xFFFFDAD6)
val backgroundDark = Color(color = 0xFF0D150C)
val onBackgroundDark = Color(color = 0xFFDCE5D6)
val surfaceDark = Color(color = 0xFF0D150C)
val onSurfaceDark = Color(color = 0xFFDCE5D6)
val surfaceVariantDark = Color(color = 0xFF3D4A3A)
val onSurfaceVariantDark = Color(color = 0xFFBBCBB6)
val outlineDark = Color(color = 0xFF869582)
val outlineVariantDark = Color(color = 0xFF3D4A3A)
val scrimDark = Color(color = 0xFF000000)
val inverseSurfaceDark = Color(color = 0xFFDCE5D6)
val inverseOnSurfaceDark = Color(color = 0xFF2A3328)
val inversePrimaryDark = Color(color = 0xFF006E1F)
val surfaceDimDark = Color(color = 0xFF0D150C)
val surfaceBrightDark = Color(color = 0xFF333C31)
val surfaceContainerLowestDark = Color(color = 0xFF081008)
val surfaceContainerLowDark = Color(color = 0xFF151E14)
val surfaceContainerDark = Color(color = 0xFF192218)
val surfaceContainerHighDark = Color(color = 0xFF242C22)
val surfaceContainerHighestDark = Color(color = 0xFF2E372D)
